spring.application.name=auth-service

server.port=${PORT:8081}
server.error.include-message=always
server.error.include-binding-errors=always
jwt.secret=ThisIsMySuperSecretKeyForJwtTokenGeneration123456789012345

spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/auth_service?sslMode=VERIFY_IDENTITY}
spring.datasource.username=${DB_USERNAME:3N8KrfUxUKX32b6.root}
spring.datasource.password=${DB_PASSWORD:Okw4Hb2lmCw7gIqg}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:465}
spring.mail.username=${SPRING_MAIL_USERNAME:Ritik.sde.sharma@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mtvxatswnutweqgp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000
