spring:
  application:
    name: gateway-service
  codec:
    max-in-memory-size: 25MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"


jwt:
  secret: ThisIsMySuperSecretKeyForJwtTokenGeneration123456789012345
